version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "npm"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "vitest"
          - "eslint*"
          - "prettier*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "@astrojs/*"
          - "astro"
          - "hono"
          - "wrangler"
          - "react"
          - "react-dom"
        update-types:
          - "patch"
    ignore:
      # Major version updates sollten manuell geprüft werden
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore"
      include: "scope"
