name: Auth DryRun (Local Worker + Smoke)

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'test-suite-v2/**'
      - '.github/workflows/auth-dryrun.yml'
      - 'wrangler.toml'
      - 'package.json'

permissions:
  contents: read

concurrency:
  group: auth-dryrun-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dryrun:
    name: Local Worker DryRun + Auth Smoke
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build worker (dev)
        run: npm run build:worker:dev

      - name: Start Wrangler Dev (background)
        run: |
          nohup sh -c 'npm run dev:worker:nobuild -- --env development --port 8787 > wrangler.out 2>&1 & echo $! > wrangler.pid' &
          sleep 3

      - name: Wait for server and health probe
        env:
          BASE_URL: http://127.0.0.1:8787
        run: |
          # Wait until server responds
          for i in $(seq 1 60); do
            if curl -fsS "${BASE_URL}" >/dev/null 2>&1; then
              break
            fi
            sleep 1
          done
          # Health check (script uses BASE_URL)
          npm run health-check

      - name: Run Playwright Auth Smoke (Chromium)
        env:
          TEST_BASE_URL: http://127.0.0.1:8787
        run: npm run test:e2e:chromium -- test-suite-v2/src/e2e/auth/welcome-redirect.spec.ts

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: test-suite-v2/reports/playwright-html-report
          retention-days: 7

      - name: Stop Wrangler Dev
        if: always()
        run: |
          if [ -f wrangler.pid ]; then
            kill $(cat wrangler.pid) || true
          fi
