name: E2E Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'migrations/**'
      - 'package.json'
      - 'astro.config.mjs'
      - 'wrangler.toml'
      - 'test-suite-v2/**'
      - 'tests/e2e/**'
      - 'playwright.config.ts'
      - 'vitest.config.ts'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'migrations/**'
      - 'package.json'
      - 'astro.config.mjs'
      - 'wrangler.toml'
      - 'test-suite-v2/**'
      - 'tests/e2e/**'
      - 'playwright.config.ts'
      - 'vitest.config.ts'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Verify TEST_BASE_URL
      run: |
        if [ -z "${TEST_BASE_URL}" ]; then
          echo "TEST_BASE_URL ist nicht gesetzt. Bitte in GitHub > Settings > Variables > Actions eine Variable TEST_BASE_URL (z.B. https://staging.hub-evolution.com) hinterlegen."
          exit 1
        fi
      env:
        TEST_BASE_URL: ${{ vars.TEST_BASE_URL }}

    - name: Run Playwright Tests
      run: npm run test:e2e
      env:
        TEST_BASE_URL: ${{ vars.TEST_BASE_URL }}

    - name: i18n Empty Strings Report
      run: npm run i18n:report | tee i18n-empty-report.txt

    - name: Upload i18n report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: i18n-empty-report
        path: i18n-empty-report.txt
        retention-days: 30

    - name: Upload report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          test-suite-v2/reports/playwright-html-report/
          test-suite-v2/reports/playwright-results.json
          test-suite-v2/reports/playwright-junit.xml
        retention-days: 30
